[package]
name = "osu-music-symlinker"
version = "0.1.0"
authors = ["Ron B <me@ronthecookie.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
pbr = "1.0.4"
regex = "1.5.3"
lazy_static = "1.4.0"
